### ISSUE TITLE
代码运行报错

### ISSUE THREAD

**Issue by xingxingsss** [AlanLi1997/slim-neck-by-gsconv#14]
您好，想请问一下您，用您所给的方式替换yolov5的neck部分，报这样的错误：
Traceback (most recent call last):
  File "/root/autodl-tmp/yolov5-master/train.py", line 632, in <module>
    main(opt)
  File "/root/autodl-tmp/yolov5-master/train.py", line 526, in main
    train(opt.hyp, opt, device, callbacks)
  File "/root/autodl-tmp/yolov5-master/train.py", line 123, in train
    model = Model(cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/root/autodl-tmp/yolov5-master/models/yolo.py", line 195, in __init__
    m.stride = torch.tensor([s / x.shape[-2] for x in forward(torch.zeros(1, ch, s, s))])  # forward
  File "/root/autodl-tmp/yolov5-master/models/yolo.py", line 194, in <lambda>
    forward = lambda x: self.forward(x)[0] if isinstance(m, Segment) else self.forward(x)
  File "/root/autodl-tmp/yolov5-master/models/yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/root/autodl-tmp/yolov5-master/models/yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/yolov5-master/models/common.py", line 1177, in forward
    x1 = self.gsb(self.cv1(x))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/yolov5-master/models/common.py", line 1153, in forward
    return self.conv_lighting(x) + self.shortcut(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/yolov5-master/models/common.py", line 1111, in forward
    x1 = self.cv1(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/yolov5-master/models/common.py", line 53, in forward
    return self.act(self.bn(self.conv(x)))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: dilation should be greater than zero, but got [0, 0]

进程已结束,退出代码1

修改部分：
![image](https://user-images.githubusercontent.com/94423685/196674182-3c3fdb6e-3999-4dc6-821a-e9beba9ff7ad.png)

请问是哪里出问题了呢？
torch版本为1.7.0，yolov5版本为6.2

**Comment by xingxingsss** [comment]
问题解决啦，是yolo版本的问题，换成6.1版本就好了
